### ISSUE TITLE
Prevent going back

### ISSUE THREAD

**Issue by ElisaNgLi** [Doggy-J-E/Doggy#16]
Need to find a way to prevent the user from going back after clicking the Let's Start button from the Welcome screen.

The situation should be:
Click the Let's Start button from Welcome Screen -> Go to Home Screen without the back arrow showing up.

**Comment by hyunjiLeeTech** [comment]
Let's do this issue later when we need to deploy this app. Keep this function so we can see the screen while implementing this app.
