### ISSUE TITLE
color configuration update

### ISSUE THREAD

**Issue by hyunjiLeeTech** [Doggy-J-E/Doggy#2]
Need to decide the color palette for our app and store that on /config/color.js

**Comment by ElisaNgLi** [comment]
https://coolors.co/ff9f1c-ffbf69-ffffff-cbf3f0-2ec4b6

**Comment by hyunjiLeeTech** [comment]
Closed by c20b0a1f7b9f093f688e2c4cfc5d1da7c1553c07
