### ISSUE TITLE
Create Terms & Condition Screen

### ISSUE THREAD

**Issue by hyunjiLeeTech** [Doggy-J-E/Doggy#44]
Need to mention where do we get sources
- API (https://www.thedogapi.com/)
- Pictures
- Icon

**Comment by ElisaNgLi** [comment]
Logo: https://www.freelogodesign.org/
Icons: https://ionic.io/ionicons/v4

**Comment by ElisaNgLi** [comment]
1. Modify the first loading screen to display the logo plus the name of the application
2. Delete the welcomescreen and just show the terms and condition 
 Loading with Logo -> Terms and Condition -> Home
3. Figure how to store the device when they already agree to the terms so it doesn't display anymore.
